mysql:
  host: mysql-prod.company.com
  port: 3306
  database: production_db
  username: prod_user
  password: super_secret_prod_password
  max_connections: 100
  timeout: 30
  ssl_enabled: true
  
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 60