spring:
  application:
    name: unified-config-client

logging:
  level:
    com.example.unifiedconfigclient: INFO
    org.springframework.cloud.config: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"