server:
  port: 8889

spring:
  application:
    name: unified-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///c:/Users/YTIRPAN/Documents/config/config-repo-encrypted

# Encryption configuration
encrypt:
  key: MySecretEncryptionKey123456789012

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    org.springframework.cloud.config: INFO
    com.example.unifiedconfigserver: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"